var data = {
	food:{
		list:[
			{
				img:'/static/foodImg/meirong.png',
				title:'美容养颜'
			},
			{
				img:'/static/foodImg/baojian.png',
				title:'保健调养'
			},
			{
				img:'/static/foodImg/buyang.png',
				title:'补养'
			},
			{
				img:'/static/foodImg/jianfei.png',
				title:'减肥'
			},
			{
				img:'/static/foodImg/muying.png',
				title:'母婴'
			},
			{
				img:'/static/foodImg/qijie.png',
				title:'气节'
			},
			{
				img:'/static/foodImg/shiliao.png',
				title:'食疗'
			},
			{
				img:'/static/foodImg/renqun.png',
				title:'人群功效'
			},
			{
				img:'/static/foodImg/vc.png',
				title:'维生素'
			},
			{
				img:'/static/foodImg/qita.png',
				title:'其他'
			}
		],
		content:[
			{
				url:'/static/foodImg/yimi1.png',
				title:'红豆薏仁粉',
				cont:'红豆薏仁粉红豆薏仁粉红豆薏仁粉红豆薏仁粉',
				price:'￥245',
				people:'389人付款',
				path:'detail'
			},
			{
				url:'/static/foodImg/yimi2.png',
				title:'荷叶茶',
				cont:'荷叶茶荷叶茶荷叶茶荷叶茶荷叶茶荷叶茶',
				price:'￥245',
				people:'28389人付款',
				path:'detail'
			},
			{
				url:'/static/foodImg/yimi3.png',
				title:'山野农夫',
				cont:'山野农夫山野农夫山野农夫山野农夫山野农夫',
				price:'￥245',
				people:'8389人付款',
				path:'detail'
			},
			{
				url:'/static/foodImg/yimi1.png',
				title:'红豆薏仁粉',
				cont:'红豆薏仁粉红豆薏仁粉红豆薏仁粉红豆薏仁粉',
				price:'￥245',
				people:'389人付款',
				path:'detail'
			},
			{
				url:'/static/foodImg/yimi3.png',
				title:'山野农夫',
				cont:'山野农夫山野农夫山野农夫山野农夫山野农夫',
				price:'￥245',
				people:'8389人付款',
				path:'detail'
			},
			{
				url:'/static/foodImg/yimi2.png',
				title:'荷叶茶',
				cont:'荷叶茶荷叶茶荷叶茶荷叶茶荷叶茶荷叶茶',
				price:'￥245',
				people:'28389人付款',
				path:'detail'
			}
		]
	},
	rank:{
		car:[
			{
				url:'/static/foodImg/huang.png',
				title:'东北有机红谷黄小米',
				editing:'编辑',
				price:'￥45',
				num:'x1'
			},
			{
				url:'/static/foodImg/hei.png',
				title:'东北有机红谷黑小米',
				editing:'编辑',
				price:'￥55',
				num:'x1'
			}
		]
	},
	address:[
				{
					addressName:'李雷',
					addressTel:'18404908540',
					address:'北京市海淀区西三旗桥东神州科技园B座尚学堂',
				},
				{
					addressName:'韩梅梅',
					addressTel:'18404908541',
					address:'北京市海淀区航空航天大学',
				},
				{
					addressName:'Lucy',
					addressTel:'18404908542',
					address:'北京市海淀区上奥世纪木北造型',
				},
			],
	itemList:[
				{
					title:'您的订单已完成',
					itemDa:'2016-12-01',
					itemTe:'12:00'
				},
				{
					title:'您的订单正在派送',
					itemDa:'2016-12-01',
					itemTe:'12:00'
				},
				{
					title:'您的订单正在揽收',
					itemDa:'2016-12-01',
					itemTe:'12:00'
				},
			],
	home:{
		footers:[
			{
				title:'八大零食安全隐患，你中 了几个？',
				src:"../../static/pic/01.png",
				content:"即使很多标榜“安全”的零食村上春树大额， 也存在很多隐患。",
				num:'25338',
				path:'case'
			},
			{
				title:'感冒了好衰啊...吃什么才好得快？',
				src:"../../static/pic/02.png",
				content:"冬天的感冒就仿佛是秋天的盛世嫡妃水了 落叶，春天的百花般，总是当时的发生更 按时到来。无论现在的你...",
				num:'38489'
			},
			{
				title:'感冒了好衰啊...吃什么才好得快？',
				src:"../../static/pic/02.png",
				content:"冬天的感冒就仿佛是秋天的盛世嫡妃水了 落叶，春天的百花般，总是当时的发生更 按时到来。无论现在的你...",
				num:'38489'
			}
		]
	}
	
			
}
// 我的数据
var myData={
	examination:{
	       xingxi:[
			{
				name:'减重'
			},
			{
				name:'通风'
			},
			{
				name:'血糖升高'
			},
			{
				name:'脂肪肝'
			},
			{
				name:'慢性肠胃炎'
			},
			{
				name:'慢性支气管炎'
			},
			{
				name:'血脂升高'
			},
			{
				name:'血压升高'
			}	
	 	]
  },
   information:{
   	many:[
			{	
				name:'安心食疗店',
				url:'../../../../../static/my/menu1.png',
				title:'五谷养生粥',
				editing:'增强食欲，促进消化',
				term:'七天退换',
				old:'￥26.00',
				newPrice:'￥30.00',
				num:'x1',
				total:'共1件商品 合计：￥30:00(含运费￥0.00)'
			},
			{	
				name:'安心食疗店',
				url:'../../../../../static/my/menu2.png',
				title:'药膳汤',
				editing:'治疗疾病，养生保健',
				term:'七天退换',
				old:'￥54.00',
				newPrice:'￥60.00',
				num:'x1',
				total:'共1件商品 合计：￥54:00(含运费￥0.00)'
			},
			{	
				name:'安心食疗店',
				url:'../../../../../static/my/menu3.png',
				title:'药膳鸡汤',
				editing:'养心安神、抗疲劳、养颜美容',
				term:'七天退换',
				old:'￥48.00',
				newPrice:'￥52.00',
				num:'x1',
				total:'共1件商品 合计：￥48:00(含运费￥0.00)'
			}
			
		
		]
   }
}

module.exports = {	data, myData }
